//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Invetory_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars_master
    {
        public int id { get; set; }
        public string car_brand { get; set; }
        public string car_model { get; set; }
        public Nullable<decimal> year { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> isNew { get; set; }
        public Nullable<int> user_Id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
